Build rpm on older CentOS6 version Test on newest CentOS6 version
Error: Package: st2chatops-2.4dev-5.x86_64 (/st2chatops-2.4dev-5.x86_64)
           Requires: libicui18n.so.52()(64bit)