Add 'libicu' dev package, required for the build
Fixing the build optional dependency:
 ```
 make[2]: Entering directory `/root/st2chatops/node_modules/node-icu-charset-detector/build'
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
../node-icu-charset-detector.cpp:7:28: fatal error: unicode/ucsdet.h: No such file or directory
 #include <unicode/ucsdet.h>
 ```